export const SHOW_SIDE_MENU = "SHOW_SIDE_MENU";
export const ACTIVE_COMPONENT = "ACTIVE_COMPONENT";
export const IS_CREATED = "IS_CREATED";
export const SHOW_LOVEJOURNEY_MODAL = "SHOW_LOVEJOURNEY_MODAL";
export const IS_LOVEJOURNEY_EDIT = "IS_LOVEJOURNEY_EDIT";
export const SINGLE_LOVEJOURNEY = "SINGLE_LOVEJOURNEY";
export const LOVEJOURNEY_ID = "LOVEJOURNEY_ID";
export const SHOW_DELETE_CONFIRMATION = "SHOW_DELETE_CONFIRMATION";
