POST http://localhost:5000/api/users
Content-Type: application/json

    {
        "name": "spiderman",
        "email": "spider@gmail.com",
        "password": "spider",
        "pic": "test.jpg"

    }

###
POST http://localhost:5000/api/users/login
Content-Type: application/json

    {

        "email": "spider@gmail.com",
        "password": "spider"


    }

###
GET http://localhost:5000/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMmYxZDYxNDViMzgzMzVmOWViYzBkMyIsImlhdCI6MTY0NzMwMjI4OCwiZXhwIjoxNjQ3Mzg4Njg4fQ.R3mU2j0l8pDlXQy6cey__7Lp8zIW452QwHYxgmkCWeI

###
POST http://localhost:5000/api/notes/create
Content-Type: application/json

    {
        "title": "test",
        "content": "test",
        "category": "test"
    }

###
POST http://localhost:5000/api/users/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzEzMDQyYWI2NGIwNTFkYzVlMjNmZCIsImlhdCI6MTY0ODM4NDQ1NCwiZXhwIjoxNjQ4NDcwODU0fQ.m2j690D_wSgTCyIebBKXWoXcmU_t8_yo2dGp9VaWIU0



    {
        "name": "spiderman",
        "email": "duck@duck.go",
        "password": "duck"
    }

###
GET http://localhost:5000/api/invitations/userid/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzEzMDQyYWI2NGIwNTFkYzVlMjNmZCIsImlhdCI6MTY0ODM4NDQ1NCwiZXhwIjoxNjQ4NDcwODU0fQ.m2j690D_wSgTCyIebBKXWoXcmU_t8_yo2dGp9VaWIU0

###
GET http://localhost:5000/api/invitations/id/62409a1fb2ed30181053bbb8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzEzMDQyYWI2NGIwNTFkYzVlMjNmZCIsImlhdCI6MTY0ODM4NDQ1NCwiZXhwIjoxNjQ4NDcwODU0fQ.m2j690D_wSgTCyIebBKXWoXcmU_t8_yo2dGp9VaWIU0

###
DELETE http://localhost:5000/api/invitations/id/62409a1fb2ed30181053bbb8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzEzMDQyYWI2NGIwNTFkYzVlMjNmZCIsImlhdCI6MTY0ODM4NDQ1NCwiZXhwIjoxNjQ4NDcwODU0fQ.m2j690D_wSgTCyIebBKXWoXcmU_t8_yo2dGp9VaWIU0


###
POST http://localhost:5000/api/invitations/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzEzMDQyYWI2NGIwNTFkYzVlMjNmZCIsImlhdCI6MTY0ODQ1NDgzNCwiZXhwIjoxNjQ4NTQxMjM0fQ.htTJUeAHLAY-oH4CjYA1F5QMVtpS4B1VpDWne2JV4Gc

    {
        "slug": "test5",
        "tema": "test",
        "namaLengkapPria": "Omar",
        "namaPria": "Omar Abdurahman",
        "namaLengkapWanita": "Hana Aisyah",
        "namaWanita": "Hana"

    }

###
GET http://localhost:5000/api/invitations/id/62416d38e19af2337e6d8dd0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzEzMDQyYWI2NGIwNTFkYzVlMjNmZCIsImlhdCI6MTY0ODQ1NDgzNCwiZXhwIjoxNjQ4NTQxMjM0fQ.htTJUeAHLAY-oH4CjYA1F5QMVtpS4B1VpDWne2JV4Gc

###
PUT http://localhost:5000/api/invitations/id/62416d38e19af2337e6d8dd0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzEzMDQyYWI2NGIwNTFkYzVlMjNmZCIsImlhdCI6MTY0ODQ1NDgzNCwiZXhwIjoxNjQ4NTQxMjM0fQ.htTJUeAHLAY-oH4CjYA1F5QMVtpS4B1VpDWne2JV4Gc

{
        "slug": "test6",
        "tema": "tema01",
        "namaLengkapPria": "Omar1",
        "namaPria": "Omar Abdurahman1",
        "namaLengkapWanita": "Hana Aisyah1",
        "namaWanita": "Hana1"

    }

###
GET http://localhost:5000/api/invitations/slug/test6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzEzMDQyYWI2NGIwNTFkYzVlMjNmZCIsImlhdCI6MTY0ODQ1NDgzNCwiZXhwIjoxNjQ4NTQxMjM0fQ.htTJUeAHLAY-oH4CjYA1F5QMVtpS4B1VpDWne2JV4Gc
