POST http://localhost:5000/api/users
Content-Type: application/json

    {
        "name": "spiderman",
        "email": "spider@gmail.com",
        "password": "spider",
        "pic": "test.jpg"

    }


###
POST http://localhost:5000/api/users/login
Content-Type: application/json

    {

        "email": "spider@gmail.com",
        "password": "spider"


    }

###
GET http://localhost:5000/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMmYxZDYxNDViMzgzMzVmOWViYzBkMyIsImlhdCI6MTY0NzMwMjI4OCwiZXhwIjoxNjQ3Mzg4Njg4fQ.R3mU2j0l8pDlXQy6cey__7Lp8zIW452QwHYxgmkCWeI

###
POST http://localhost:5000/api/notes/create
Content-Type: application/json

    {
        "title": "test",
        "content": "test",
        "category": "test"
    }

###
POST http://localhost:5000/api/users/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzEzMDQyYWI2NGIwNTFkYzVlMjNmZCIsImlhdCI6MTY0ODM4NDQ1NCwiZXhwIjoxNjQ4NDcwODU0fQ.m2j690D_wSgTCyIebBKXWoXcmU_t8_yo2dGp9VaWIU0



    {
        "name": "spiderman",
        "email": "duck@duck.go",
        "password": "duck"
    }

###
GET http://localhost:5000/api/invitations/userid/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzEzMDQyYWI2NGIwNTFkYzVlMjNmZCIsImlhdCI6MTY0OTEyMzc3OCwiZXhwIjoxNjQ5MjEwMTc4fQ.uDGs0AKHUljGmHK_0fGvq3-TGtFGaK8oYhtZnUa-s20
###
DELETE http://localhost:5000/api/invitations/id/6243b2552e349ef70c9d4c62
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzEzMDQyYWI2NGIwNTFkYzVlMjNmZCIsImlhdCI6MTY0OTEyMzc3OCwiZXhwIjoxNjQ5MjEwMTc4fQ.uDGs0AKHUljGmHK_0fGvq3-TGtFGaK8oYhtZnUa-s20

###
GET http://localhost:5000/api/invitations/id/624403de1cc9c0c51e384681
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzEzMDQyYWI2NGIwNTFkYzVlMjNmZCIsImlhdCI6MTY0OTEyMzc3OCwiZXhwIjoxNjQ5MjEwMTc4fQ.uDGs0AKHUljGmHK_0fGvq3-TGtFGaK8oYhtZnUa-s20

###

GET http://localhost:5000/api/invitations/public/id/624403de1cc9c0c51e384681




###
PUT http://localhost:5000/api/invitations/id/6241193ebf3ef12371f76f64
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDI5ZWQyNzA0ODk3OWRmOGIyYzBjZiIsImlhdCI6MTY0ODUzMzIxMywiZXhwIjoxNjQ4NjE5NjEzfQ.Oj0jU-6np_WK_QPiViof-zBgpBCMo9shAzYLlfmkyOg

    {
        "slug": "test3",
        "tema": "test",
        "namaLengkapPria": "Omar Abdurrahman",
        "namaPria": "Omar",
        "namaLengkapWanita": "Hana Aisyah",
        "namaWanita": "Hani",
        "waktuAkad": "2020-06-01"

    }




###
POST http://localhost:5000/api/invitations/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDI5ZWQyNzA0ODk3OWRmOGIyYzBjZiIsImlhdCI6MTY0ODUzMzIxMywiZXhwIjoxNjQ4NjE5NjEzfQ.Oj0jU-6np_WK_QPiViof-zBgpBCMo9shAzYLlfmkyOg

    {
        "slug": "slug01"        
    }

// ------- Provider API Testing ----------
// createProvider
###
POST http://localhost:5000/api/provider/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTAwZjlkMGI0MDZjZDUzMDVhMzZkZCIsImlhdCI6MTY0OTQxNDA2MX0.UCVVbbT5Bfl6GbXz90M3yJU6TvPZPKio-yoNoeysULM

{
    "providerName": "test02"
}

// getProvider
###
GET http://localhost:5000/api/provider
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTAwZjlkMGI0MDZjZDUzMDVhMzZkZCIsImlhdCI6MTY0OTQxNDA2MX0.UCVVbbT5Bfl6GbXz90M3yJU6TvPZPKio-yoNoeysULM

// getProviderById
###
GET http://localhost:5000/api/provider/6250163dc7f95587a563c39e

// deleteProviderById
###
DELETE http://localhost:5000/api/provider/6250163dc7f95587a563c39e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTAwZjlkMGI0MDZjZDUzMDVhMzZkZCIsImlhdCI6MTY0OTQxNDA2MX0.UCVVbbT5Bfl6GbXz90M3yJU6TvPZPKio-yoNoeysULM

// updateProviderById
###
PUT http://localhost:5000/api/provider/6250163dc7f95587a563c39e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTAwZjlkMGI0MDZjZDUzMDVhMzZkZCIsImlhdCI6MTY0OTQxNDA2MX0.UCVVbbT5Bfl6GbXz90M3yJU6TvPZPKio-yoNoeysULM

{
    "providerName": "test01",
     "music": [{
        "title": "Sebiru Hari Ini",
        "artist": "Edcoustic",
        "url": "https://res.cloudinary.com/dashgfoiauhgjfeagf"
    },
    {
        "title": "All of Me",
        "artist": "John Legend",
        "url": "https://res.cloudinary.com/dashgfoiauhgjfeagf"
    },

  {
    "title": "Barakallah",
    "artist": "Maher Zein",
    "url": "https://www.youtube.com/watch?v=dQw4w9WgXcQbb"
  }
    ],
    "theme": [   
        {    
    "image":
      "https://images.unsplash.com/photo-1518791841217-8f162f1e1131?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60",
    "title": "Tema 1",
    "tag": ["slide", "customable"],
    "description": "Tema dengan nuansa vintage dengan tampilan minimalis.",
    "demoLink": "https://www.jazuaatu.com/tema01"
  },
  {
    
    "image":
      "https://images.unsplash.com/photo-1518791841217-8f162f1e1131?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60",
    "title": "Tema 2",
    "tag": ["scroll", "customable"],
    "description": "Tema dengan nuansa vintage dengan tampilan minimalis.",
    "demoLink": "https://www.jazuaatu.com/tema02"
  },
  {
    
    "image":
      "https://images.unsplash.com/photo-1518791841217-8f162f1e1131?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60",
    "title": "Tema 3",
    "tag": ["slide"],
    "description": "Tema dengan nuansa vintage dengan tampilan minimalis.",
    "demoLink": "https://www.jazuaatu.com/tema03"
  } 
    ]
}

// --------- User API Testing ----------
// Get User Admin
###
GET http://localhost:5000/api/users/useradmin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTAwZjlkMGI0MDZjZDUzMDVhMzZkZCIsImlhdCI6MTY0OTQxNDA2MX0.UCVVbbT5Bfl6GbXz90M3yJU6TvPZPKio-yoNoeysULM


// Update User Admin
###
POST http://localhost:5000/api/users/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTAwZjlkMGI0MDZjZDUzMDVhMzZkZCIsImlhdCI6MTY0OTQxNDA2MX0.UCVVbbT5Bfl6GbXz90M3yJU6TvPZPKio-yoNoeysULM

{
        "_id": "62500f9d0b406cd5305a36dd",
    "name": "Super Admin",
    "email": "superadmin@jauzatu.com",
    "isAdmin": true,
    "accountType": "Silver",
    "pic": "https://icon-library.com/images/anonymous-avatar-icon/anonymous-avatar-icon-25.jpg"
}

// Get All Users
###
GET http://localhost:5000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTAwZjlkMGI0MDZjZDUzMDVhMzZkZCIsImlhdCI6MTY0OTQxNDA2MX0.UCVVbbT5Bfl6GbXz90M3yJU6TvPZPKio-yoNoeysULM
 


